# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsEc2Ssh < Formula
  desc "SSH helper for connecting to EC2 instances via EC2 Instance Connect"
  homepage "https://github.com/mrtimp/aws-ec2-ssh"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/aws-ec2-ssh/releases/download/1.0.0/aws-ec2-ssh_1.0.0_darwin_amd64.tar.gz"
      sha256 "7eb9e5d384e1f76534c80c0e91c1247ec963eef3217c478e62bb126df952730a"

      def install
        bin.install "ec2-ssh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/aws-ec2-ssh/releases/download/1.0.0/aws-ec2-ssh_1.0.0_darwin_arm64.tar.gz"
      sha256 "2bc8ed9420d099c63d2ad83bd461e650f8db5c1983f8ca07c91a8301cc79fa30"

      def install
        bin.install "ec2-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-ec2-ssh/releases/download/1.0.0/aws-ec2-ssh_1.0.0_linux_amd64.tar.gz"
      sha256 "0df31f1b86e11ed839d09ea70f4eec45e2ff920dde861822353fce1fe27c0c25"
      def install
        bin.install "ec2-ssh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-ec2-ssh/releases/download/1.0.0/aws-ec2-ssh_1.0.0_linux_arm64.tar.gz"
      sha256 "e3e9ff7d5d871e011b2fae9b7adf50e6f5bcbe98dd0de18aa6eb55a55b0efd04"
      def install
        bin.install "ec2-ssh"
      end
    end
  end
end
