# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsoConfig < Formula
  desc "Automatically generate AWS profiles for accounts and roles you have access to via SSO/IAM Identity Center"
  homepage "https://github.com/mrtimp/aws-sso-config"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/aws-sso-config/releases/download/1.0.0/aws-sso-config_1.0.0_darwin_amd64.tar.gz"
      sha256 "b15adc2926b0d600fe7bb711a6cd74aa3f5fa4137a7c2bec5678c0985ed90c16"

      def install
        bin.install "aws-sso-config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/aws-sso-config/releases/download/1.0.0/aws-sso-config_1.0.0_darwin_arm64.tar.gz"
      sha256 "6d5e26fff9e7899badf2c3fc96fce21881cd9ae1766f80cce7dc997803aa83a5"

      def install
        bin.install "aws-sso-config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrtimp/aws-sso-config/releases/download/1.0.0/aws-sso-config_1.0.0_linux_amd64.tar.gz"
        sha256 "cfc70649ae5da2e0f0428e2700d05f19e6b7e6c7928ab3304aaa560a32ac7ef2"

        def install
          bin.install "aws-sso-config"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrtimp/aws-sso-config/releases/download/1.0.0/aws-sso-config_1.0.0_linux_arm64.tar.gz"
        sha256 "3cd68b1ba256ea3166c5c43eb00c7cdd5e41e2d42db6ecc3739026779872f22e"

        def install
          bin.install "aws-sso-config"
        end
      end
    end
  end
end
