# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCredentialsReporter < Formula
  desc "Retrieves credential reports for multiple AWS accounts"
  homepage "https://github.com/mrtimp/aws-credentials-reporter"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/aws-credentials-reporter/releases/download/1.0.0/aws-credentials-reporter_1.0.0_darwin_amd64.tar.gz"
      sha256 "ec2cf97ce2db4d9de7b8dc2c253707b47bfc70e5dd8923d96659d77685c0571d"

      def install
        bin.install "aws-credentials-reporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/aws-credentials-reporter/releases/download/1.0.0/aws-credentials-reporter_1.0.0_darwin_arm64.tar.gz"
      sha256 "69d793304aa941727768532e4f087af2de63e5cb356256f57ec8719b3da1d4b5"

      def install
        bin.install "aws-credentials-reporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrtimp/aws-credentials-reporter/releases/download/1.0.0/aws-credentials-reporter_1.0.0_linux_amd64.tar.gz"
        sha256 "4bcd50fe42ea118a87cb67466070e11ca16d26fc91ecfc605864dfc13efe476a"

        def install
          bin.install "aws-credentials-reporter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrtimp/aws-credentials-reporter/releases/download/1.0.0/aws-credentials-reporter_1.0.0_linux_arm64.tar.gz"
        sha256 "2739c33381591e38dda87bac409d7d578ff429dbc5f69a3a36f2c470bbc00be9"

        def install
          bin.install "aws-credentials-reporter"
        end
      end
    end
  end
end
