# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsBackupRoute53 < Formula
  desc "Backup AWS Route 53 zones to CSV"
  homepage "https://github.com/mrtimp/aws-backup-route53"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/aws-backup-route53/releases/download/1.0.0/aws-backup-route53_1.0.0_darwin_amd64.tar.gz"
      sha256 "f98fd7464e03262fca8e9c57c19465219583b541f0376be75a59c337b1691429"

      def install
        bin.install "aws-backup-route53"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/aws-backup-route53/releases/download/1.0.0/aws-backup-route53_1.0.0_darwin_arm64.tar.gz"
      sha256 "530edb6571971f087c7522aa25eb0937e5300b5df3caa2ef643c6ebeb5c50f13"

      def install
        bin.install "aws-backup-route53"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-backup-route53/releases/download/1.0.0/aws-backup-route53_1.0.0_linux_amd64.tar.gz"
      sha256 "0e013eda1766ae2187adcc57ce18df87887b7c4bd8a2476e24580cf72629b154"
      def install
        bin.install "aws-backup-route53"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-backup-route53/releases/download/1.0.0/aws-backup-route53_1.0.0_linux_arm64.tar.gz"
      sha256 "a3f01260010af3536e18615ce1f6256e763ce5891533e84f965656c5c449f6d2"
      def install
        bin.install "aws-backup-route53"
      end
    end
  end
end
