# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCloneLambda < Formula
  desc "Retrieves credential reports for multiple AWS accounts"
  homepage "https://github.com/mrtimp/aws-credentials-reporter"
  version "0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/aws-clone-lambda/releases/download/0.9/aws-clone-lambda_0.9_darwin_amd64.tar.gz"
      sha256 "98f62a8bbe6ab0e06b55c2c968e8812d80fa1f2c6a4f897b81479a52f965c6a0"

      def install
        bin.install "aws-clone-lambda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/aws-clone-lambda/releases/download/0.9/aws-clone-lambda_0.9_darwin_arm64.tar.gz"
      sha256 "71bfeee72c6a621bdbb64650a1bba8816f284f059f8e429cb57ed20037202873"

      def install
        bin.install "aws-clone-lambda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-clone-lambda/releases/download/0.9/aws-clone-lambda_0.9_linux_amd64.tar.gz"
      sha256 "161016c082f7292af44771b5d1010e53f680539b29e1b4c4a8be31dfb37f6555"
      def install
        bin.install "aws-clone-lambda"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/aws-clone-lambda/releases/download/0.9/aws-clone-lambda_0.9_linux_arm64.tar.gz"
      sha256 "02e7286bd47da8257c748c9e5248b846450ff6ddbd5f857e2f51fd199f532afa"
      def install
        bin.install "aws-clone-lambda"
      end
    end
  end
end
