# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gojen < Formula
  desc "Go project generator"
  homepage "https://github.com/mrtimp/gojen"
  version "0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/gojen/releases/download/0.1/gojen_0.1_darwin_amd64.tar.gz"
      sha256 "31edd3de6d8d601c4547b5d3c1f8b321eaa63e708f0ab0824f9950b19de9ae12"

      def install
        bin.install "gojen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/gojen/releases/download/0.1/gojen_0.1_darwin_arm64.tar.gz"
      sha256 "f78072d990c2b08ebc0e6ef00b441d0f75914f07ca4b68adcd84f96519b3e698"

      def install
        bin.install "gojen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/gojen/releases/download/0.1/gojen_0.1_linux_amd64.tar.gz"
      sha256 "4353c0f53c78178e129259ecc1b032315bd095a17cebb31a1a236441ff538245"
      def install
        bin.install "gojen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/gojen/releases/download/0.1/gojen_0.1_linux_arm64.tar.gz"
      sha256 "8a911a52d5d40f3e566872cbd345875600fd80af07bd86ade75448906acc5e8e"
      def install
        bin.install "gojen"
      end
    end
  end
end
