# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraProfile < Formula
  desc "Automatically set the AWS_PROFILE for Terraform/Terragrunt based on configuration"
  homepage "https://github.com/mrtimp/terra-profile"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrtimp/terra-profile/releases/download/1.0.0/terra-profile_1.0.0_darwin_amd64.tar.gz"
      sha256 "bf518a200ebe2eea49f67ea4792c2aa0c5c73022461716a7ee0bb8df851b478c"

      def install
        bin.install "terra-profile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrtimp/terra-profile/releases/download/1.0.0/terra-profile_1.0.0_darwin_arm64.tar.gz"
      sha256 "ac5837a6b19d4a820fb77caa5c2194f7ea9c5adc59641d53a1980982fa20891f"

      def install
        bin.install "terra-profile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/terra-profile/releases/download/1.0.0/terra-profile_1.0.0_linux_amd64.tar.gz"
      sha256 "e6ceead0b536b6747ad291536e5e2935681e94a6dc4f29c487d3a2fb8dd9146c"
      def install
        bin.install "terra-profile"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrtimp/terra-profile/releases/download/1.0.0/terra-profile_1.0.0_linux_arm64.tar.gz"
      sha256 "1d9007a7ad79f389d09c0a2f0652d405e39d0d86da580f293ff827153847f901"
      def install
        bin.install "terra-profile"
      end
    end
  end
end
